# -*- coding: utf-8 -*-
"""Widget_Generators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAtPfjFiUXoNvT9aEZguWClJfRkWuNcj
"""

import ipywidgets as widgets
import pandas as pd

# Load data from CSV file
data = pd.read_csv('Data_generators.csv')
data = data.transpose()
data = data.reset_index()
# data.iloc[0, 0] = 'Parameters'

# Create a container to hold the widgets
container = widgets.GridBox(layout=widgets.Layout(grid_template_columns="repeat(auto-fit, minmax(60px, 90px))"))

g_names = data.iloc[0].tolist()
p_names = data.iloc[:, 0].tolist()
p_labels = [widgets.Label(value=name) for name in p_names]

container.children += tuple(p_labels)

grid_list = []

for column in range(len(data.columns)):
  if column == 0:
    g_name = 'Parameters'
  else:
    g_name = g_names[column]

  g_widget = [widgets.Label(value=g_name)]

  for row in range(1, len(data)):
      p_value = data.iloc[row, column]

      try:
          value = float(p_value)
          widget = widgets.FloatText(value=value, layout=widgets.Layout(width='auto'))
      except ValueError:
          widget = widgets.Label(value=p_value)

      g_widget.append(widget)

  grid_list.append(g_widget)

container.children = [widgets.VBox(children=row) for row in grid_list]



button = widgets.Button(description='Guardar cambios')

def updateCSV(_):
  global data2
  for column in range(len(data.columns)):
      for row in range(1, len(data)):
          widget = grid_list[column][row]
          new_value = widget.value
          data.iloc[row, column] = new_value
  data2 = data.transpose()
  data2 = data2.set_index(data2.columns[0])
  data2.columns = data2.iloc[0]
  data2 = data2[1:]
  data2.index.name = 'g'
  print('a')
  data2.to_csv('Data_generators2.csv')

button.on_click(updateCSV)



display(container, button)

data2

data = pd.read_csv('Data_generators.csv')

data

p_names